# Generated by Django 5.2.14 on 2026-05-16 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colleges', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('workshop', 'Workshop'), ('festival', 'Festival'), ('placement', 'Placement'), ('achievement', 'Achievement'), ('conference', 'Conference'), ('guest_lecture', 'Guest Lecture'), ('academic', 'Academic Event'), ('cultural', 'Cultural Event'), ('sports', 'Sports Event'), ('other', 'Other')], default='other', max_length=20)),
                ('date', models.DateField()),
                ('is_carousel', models.BooleanField(default=False)),
                ('is_reel', models.BooleanField(default=False)),
                ('is_news', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='colleges.college')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='event_media/')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('pdf', 'PDF'), ('reel', 'Reel'), ('poster', 'Poster')], default='image', max_length=10)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='events.event')),
            ],
        ),
    ]
