# Generated by Django 5.2.1 on 2026-05-28 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0001_initial'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['college', 'date'], name='idx_event_college_date'),
        ),
    ]
