# Generated by Django 5.2.1 on 2026-05-31 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_idx_event_college_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='social_media_link',
            field=models.URLField(blank=True, verbose_name='Social Media Account Link'),
        ),
    ]
