# Generated by Django 5.2.14 on 2026-05-16 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colleges', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')])),
                ('year', models.IntegerField(default=2026)),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook')], max_length=10)),
                ('caption', models.TextField(blank=True)),
                ('views', models.IntegerField(default=0)),
                ('likes', models.IntegerField(default=0)),
                ('shares', models.IntegerField(default=0)),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='top_posts/')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_posts', to='colleges.college')),
            ],
            options={
                'ordering': ['-views'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')])),
                ('year', models.IntegerField(default=2026)),
                ('instagram_views', models.IntegerField(default=0)),
                ('facebook_views', models.IntegerField(default=0)),
                ('total_views', models.IntegerField(default=0)),
                ('instagram_reach', models.IntegerField(default=0)),
                ('facebook_reach', models.IntegerField(default=0)),
                ('total_reach', models.IntegerField(default=0)),
                ('instagram_followers', models.IntegerField(default=0)),
                ('facebook_followers', models.IntegerField(default=0)),
                ('youtube_subscribers', models.IntegerField(default=0)),
                ('followers_gained', models.IntegerField(default=0)),
                ('reels_count', models.IntegerField(default=0)),
                ('graphics_count', models.IntegerField(default=0)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='colleges.college')),
            ],
            options={
                'verbose_name_plural': 'Monthly Analytics',
                'unique_together': {('college', 'month', 'year')},
            },
        ),
    ]
