# Generated by Django 5.2.1 on 2026-05-28 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_app', '0001_initial'),
        ('colleges', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='monthlyanalytics',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='monthlyanalytics',
            index=models.Index(fields=['year', 'month'], name='idx_analytics_year_month'),
        ),
        migrations.AddIndex(
            model_name='toppost',
            index=models.Index(fields=['college', 'month', 'year', 'platform'], name='idx_toppost_lookup'),
        ),
        migrations.AddIndex(
            model_name='toppost',
            index=models.Index(fields=['year', 'month'], name='idx_toppost_year_month'),
        ),
        migrations.AddConstraint(
            model_name='monthlyanalytics',
            constraint=models.UniqueConstraint(fields=('college', 'month', 'year'), name='unique_monthly_analytics'),
        ),
    ]
