# Generated by Django 5.2.1 on 2026-05-31 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_app', '0002_alter_monthlyanalytics_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='toppost',
            name='post_link',
            field=models.URLField(blank=True, verbose_name='Post Link'),
        ),
    ]
