# Generated by Django 5.2.1 on 2026-08-23 07:41

import analytics_app.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_app', '0003_toppost_post_link'),
        ('colleges', '0002_university_department_programme_college_university_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('critical', 'Critical')], default='info', max_length=10)),
                ('category', models.CharField(choices=[('missing_data', 'Missing Data'), ('big_change', 'Big Change'), ('status', 'Submission Status')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True)),
                ('month', models.IntegerField(blank=True, choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')], null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KpiTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(default=analytics_app.models.get_current_year)),
                ('metric', models.CharField(choices=[('instagram_views', 'Instagram Views'), ('facebook_views', 'Facebook Views'), ('total_views', 'Total Views'), ('instagram_reach', 'Instagram Reach'), ('facebook_reach', 'Facebook Reach'), ('total_reach', 'Total Reach'), ('instagram_followers', 'Instagram Followers'), ('facebook_followers', 'Facebook Followers'), ('youtube_subscribers', 'YouTube Subscribers'), ('followers_gained', 'Followers Gained'), ('reels_count', 'Reels Count'), ('graphics_count', 'Graphics Count')], max_length=30)),
                ('target_value', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'KPI Targets',
            },
        ),
        migrations.RemoveConstraint(
            model_name='monthlyanalytics',
            name='unique_monthly_analytics',
        ),
        migrations.AddField(
            model_name='monthlyanalytics',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics', to='colleges.department'),
        ),
        migrations.AddField(
            model_name='monthlyanalytics',
            name='programme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics', to='colleges.programme'),
        ),
        migrations.AddField(
            model_name='monthlyanalytics',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('incomplete', 'Incomplete'), ('verified', 'Verified')], db_index=True, default='pending', max_length=20, verbose_name='Submission Status'),
        ),
        migrations.AddField(
            model_name='monthlyanalytics',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monthlyanalytics',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_analytics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='monthlyanalytics',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monthlyanalytics',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_analytics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='monthlyanalytics',
            name='year',
            field=models.IntegerField(default=analytics_app.models.get_current_year),
        ),
        migrations.AlterField(
            model_name='toppost',
            name='year',
            field=models.IntegerField(default=analytics_app.models.get_current_year),
        ),
        migrations.AddIndex(
            model_name='monthlyanalytics',
            index=models.Index(fields=['status'], name='idx_analytics_status'),
        ),
        migrations.AddConstraint(
            model_name='monthlyanalytics',
            constraint=models.UniqueConstraint(condition=models.Q(('department__isnull', True), ('programme__isnull', True)), fields=('college', 'month', 'year'), name='uq_college_monthly_analytics'),
        ),
        migrations.AddConstraint(
            model_name='monthlyanalytics',
            constraint=models.UniqueConstraint(condition=models.Q(('department__isnull', False), ('programme__isnull', True)), fields=('college', 'department', 'month', 'year'), name='uq_dept_monthly_analytics'),
        ),
        migrations.AddConstraint(
            model_name='monthlyanalytics',
            constraint=models.UniqueConstraint(condition=models.Q(('programme__isnull', False)), fields=('college', 'department', 'programme', 'month', 'year'), name='uq_prog_monthly_analytics'),
        ),
        migrations.AddField(
            model_name='alert',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='colleges.college'),
        ),
        migrations.AddField(
            model_name='kpitarget',
            name='college',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpi_targets', to='colleges.college'),
        ),
        migrations.AddField(
            model_name='kpitarget',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kpi_targets', to='colleges.department'),
        ),
        migrations.AddField(
            model_name='kpitarget',
            name='programme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kpi_targets', to='colleges.programme'),
        ),
        migrations.AddConstraint(
            model_name='kpitarget',
            constraint=models.UniqueConstraint(fields=('college', 'department', 'programme', 'year', 'metric'), name='uq_kpi_target'),
        ),
    ]
