# Generated by Django 5.2.1 on 2026-07-19 11:38

import analytics_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_app', '0003_toppost_post_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlyanalytics',
            name='year',
            field=models.IntegerField(default=analytics_app.models.get_current_year),
        ),
        migrations.AlterField(
            model_name='toppost',
            name='year',
            field=models.IntegerField(default=analytics_app.models.get_current_year),
        ),
    ]
