# Generated by Django 5.2.1 on 2026-08-23 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_app', '0004_alert_kpitarget_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='dedup_key',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
