# Generated by Django 5.2.1 on 2026-07-14 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('college_admin', 'College Admin'), ('analytics_team', 'Analytics Team')], default='analytics_team', max_length=20),
        ),
    ]
