# Generated by Django 5.2.14 on 2026-05-16 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colleges', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuarterlyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quarter', models.IntegerField(choices=[(1, 'Q1 (Jan-Mar)'), (2, 'Q2 (Apr-Jun)'), (3, 'Q3 (Jul-Sep)'), (4, 'Q4 (Oct-Dec)')])),
                ('year', models.IntegerField(default=2026)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='reports/quarterly/')),
                ('ai_summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChannelCoverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField(default=2026)),
                ('channel_name', models.CharField(max_length=255)),
                ('platform', models.CharField(blank=True, max_length=50)),
                ('edition', models.CharField(blank=True, max_length=100)),
                ('link', models.URLField(blank=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_coverage', to='colleges.college')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField(default=2026)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='reports/monthly/')),
                ('generated_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_reports', to='colleges.college')),
            ],
        ),
        migrations.CreateModel(
            name='NewspaperCoverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField(default=2026)),
                ('publication', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('edition', models.CharField(blank=True, max_length=100)),
                ('page', models.CharField(blank=True, max_length=20)),
                ('headline', models.CharField(blank=True, max_length=500)),
                ('clipping', models.ImageField(blank=True, null=True, upload_to='newspaper_clippings/')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='newspaper_coverage', to='colleges.college')),
            ],
            options={
                'verbose_name_plural': 'Newspaper Coverage',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PressRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField(default=2026)),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField()),
                ('date_submitted', models.DateField()),
                ('placements', models.IntegerField(default=0)),
                ('potential_reach', models.CharField(blank=True, max_length=50)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='press_releases', to='colleges.college')),
            ],
        ),
    ]
