# Generated by Django 5.2.1 on 2026-05-18 06:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_monthlyreport_month'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedDocumentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Short label for this report', max_length=300)),
                ('quarter', models.IntegerField(choices=[(1, 'Q1 (Jan–Mar)'), (2, 'Q2 (Apr–Jun)'), (3, 'Q3 (Jul–Sep)'), (4, 'Q4 (Oct–Dec)')])),
                ('year', models.IntegerField(default=2026)),
                ('source_file', models.FileField(help_text='Upload the original detailed report (PDF or DOCX)', upload_to='reports/uploaded_sources/')),
                ('ai_summary', models.TextField(blank=True, help_text='Gemini-generated HTML summary')),
                ('output_pdf', models.FileField(blank=True, help_text='Auto-generated condensed PDF', null=True, upload_to='reports/doc_quarterly/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_doc_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Uploaded Document Report',
                'verbose_name_plural': 'Uploaded Document Reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
