# Generated by Django 5.2.1 on 2026-05-18 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_uploadeddocumentreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadeddocumentreport',
            name='source_file',
        ),
        migrations.AddField(
            model_name='uploadeddocumentreport',
            name='source_file_1',
            field=models.FileField(default='', help_text='Month 1 report PDF (required)', upload_to='reports/uploaded_sources/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploadeddocumentreport',
            name='source_file_2',
            field=models.FileField(blank=True, help_text='Month 2 report PDF (optional)', null=True, upload_to='reports/uploaded_sources/'),
        ),
        migrations.AddField(
            model_name='uploadeddocumentreport',
            name='source_file_3',
            field=models.FileField(blank=True, help_text='Month 3 report PDF (optional)', null=True, upload_to='reports/uploaded_sources/'),
        ),
    ]
