# Generated by Django 5.2.1 on 2026-05-28 17:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0001_initial'),
        ('reports', '0004_remove_uploadeddocumentreport_source_file_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channelcoverage',
            options={'ordering': ['-year', '-month']},
        ),
        migrations.AlterModelOptions(
            name='pressrelease',
            options={'ordering': ['-year', '-month']},
        ),
        migrations.AlterField(
            model_name='channelcoverage',
            name='month',
            field=models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')]),
        ),
        migrations.AlterField(
            model_name='newspapercoverage',
            name='month',
            field=models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')]),
        ),
        migrations.AlterField(
            model_name='pressrelease',
            name='month',
            field=models.IntegerField(choices=[(1, 'January'), (2, 'February'), (3, 'March'), (4, 'April'), (5, 'May'), (6, 'June'), (7, 'July'), (8, 'August'), (9, 'September'), (10, 'October'), (11, 'November'), (12, 'December')]),
        ),
        migrations.AddIndex(
            model_name='channelcoverage',
            index=models.Index(fields=['college', 'month', 'year'], name='idx_channel_col_month_year'),
        ),
        migrations.AddIndex(
            model_name='monthlyreport',
            index=models.Index(fields=['year', 'month'], name='idx_monthlyreport_year_month'),
        ),
        migrations.AddIndex(
            model_name='newspapercoverage',
            index=models.Index(fields=['college', 'month', 'year'], name='idx_newspaper_col_month_year'),
        ),
        migrations.AddIndex(
            model_name='newspapercoverage',
            index=models.Index(fields=['year', 'month'], name='idx_newspaper_year_month'),
        ),
        migrations.AddIndex(
            model_name='pressrelease',
            index=models.Index(fields=['college', 'month', 'year'], name='idx_pr_col_month_year'),
        ),
        migrations.AddIndex(
            model_name='pressrelease',
            index=models.Index(fields=['year', 'month'], name='idx_pressrelease_year_month'),
        ),
        migrations.AddIndex(
            model_name='uploadeddocumentreport',
            index=models.Index(fields=['year', 'quarter'], name='idx_uploadeddoc_year_quarter'),
        ),
        migrations.AddConstraint(
            model_name='monthlyreport',
            constraint=models.UniqueConstraint(fields=('college', 'month', 'year'), name='unique_monthly_report'),
        ),
    ]
