# Generated by Django 5.2.1 on 2026-07-14 12:40

import datetime
import django.db.models.deletion
import reports.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_alter_channelcoverage_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BatchUploadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('social_media', 'Social Media'), ('digital_print', 'Digital Print'), ('physical_newspaper', 'Physical Newspaper')], max_length=50)),
                ('file', models.FileField(upload_to='reports/batch_uploaded_sources/')),
                ('filename', models.CharField(max_length=255)),
                ('extracted_json', models.TextField(blank=True, help_text='JSON data extracted by Gemini for this specific file')),
                ('status', models.CharField(default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AlterField(
            model_name='channelcoverage',
            name='year',
            field=models.IntegerField(default=reports.models.get_current_year),
        ),
        migrations.AlterField(
            model_name='monthlyreport',
            name='year',
            field=models.IntegerField(default=reports.models.get_current_year),
        ),
        migrations.AlterField(
            model_name='newspapercoverage',
            name='year',
            field=models.IntegerField(default=reports.models.get_current_year),
        ),
        migrations.AlterField(
            model_name='pressrelease',
            name='year',
            field=models.IntegerField(default=reports.models.get_current_year),
        ),
        migrations.AlterField(
            model_name='quarterlyreport',
            name='quarter',
            field=models.IntegerField(choices=[(1, 'Q1 (Jan–Mar)'), (2, 'Q2 (Apr–Jun)'), (3, 'Q3 (Jul–Sep)'), (4, 'Q4 (Oct–Dec)')]),
        ),
        migrations.AlterField(
            model_name='quarterlyreport',
            name='year',
            field=models.IntegerField(default=reports.models.get_current_year),
        ),
        migrations.AlterField(
            model_name='uploadeddocumentreport',
            name='year',
            field=models.IntegerField(default=reports.models.get_current_year),
        ),
        migrations.CreateModel(
            name='AnnualCategoryReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Short label for this report', max_length=300)),
                ('start_date', models.DateField(default=datetime.date(2025, 6, 1))),
                ('end_date', models.DateField(default=datetime.date(2026, 7, 31))),
                ('ai_summary', models.TextField(blank=True, help_text='Gemini-generated HTML report content')),
                ('output_pdf', models.FileField(blank=True, help_text='Generated PDF report file', null=True, upload_to='reports/annual_summaries/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='annual_category_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
