# Generated by Django 5.2.1 on 2026-07-17 16:02

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0001_initial'),
        ('reports', '0005_alter_channelcoverage_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SeminarEventReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Short label/title for the seminar/event', max_length=300)),
                ('date', models.DateField(default=datetime.date.today)),
                ('speaker_name', models.CharField(blank=True, help_text='Name of the speaker/faculty', max_length=255)),
                ('audio_file', models.FileField(blank=True, help_text='Recorded voice audio file', null=True, upload_to='reports/seminars/audio/')),
                ('transcript_text', models.TextField(blank=True, help_text='Optional text transcript or notes of the seminar speech')),
                ('document_file_1', models.FileField(blank=True, help_text='Supporting document 1 (PDF)', null=True, upload_to='reports/seminars/docs/')),
                ('document_file_2', models.FileField(blank=True, help_text='Supporting document 2 (PDF)', null=True, upload_to='reports/seminars/docs/')),
                ('document_file_3', models.FileField(blank=True, help_text='Supporting document 3 (PDF)', null=True, upload_to='reports/seminars/docs/')),
                ('social_media_posts', models.TextField(blank=True, help_text='Social media post contents, notes, or links')),
                ('photo_1', models.ImageField(blank=True, null=True, upload_to='reports/seminars/photos/')),
                ('photo_2', models.ImageField(blank=True, null=True, upload_to='reports/seminars/photos/')),
                ('photo_3', models.ImageField(blank=True, null=True, upload_to='reports/seminars/photos/')),
                ('photo_4', models.ImageField(blank=True, null=True, upload_to='reports/seminars/photos/')),
                ('photo_5', models.ImageField(blank=True, null=True, upload_to='reports/seminars/photos/')),
                ('ai_summary', models.TextField(blank=True, help_text='Gemini-generated HTML report summary')),
                ('output_pdf', models.FileField(blank=True, help_text='Generated PDF report', null=True, upload_to='reports/seminars/pdf/')),
                ('status', models.CharField(default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seminar_reports', to='colleges.college')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seminar_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]