# Generated by Django 5.2.1 on 2026-09-07 15:51

import reports.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_alter_channelcoverage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyreport',
            name='prepared_by',
            field=models.CharField(blank=True, help_text='Name of the person who prepared this report', max_length=200),
        ),
        migrations.AddField(
            model_name='monthlyreport',
            name='report_title',
            field=models.CharField(blank=True, help_text='Custom title shown on the report cover page', max_length=300),
        ),
        migrations.AlterField(
            model_name='channelcoverage',
            name='year',
            field=models.IntegerField(default=reports.models.get_current_year),
        ),
        migrations.AlterField(
            model_name='monthlyreport',
            name='year',
            field=models.IntegerField(default=reports.models.get_current_year),
        ),
        migrations.AlterField(
            model_name='newspapercoverage',
            name='year',
            field=models.IntegerField(default=reports.models.get_current_year),
        ),
        migrations.AlterField(
            model_name='pressrelease',
            name='year',
            field=models.IntegerField(default=reports.models.get_current_year),
        ),
        migrations.AlterField(
            model_name='quarterlyreport',
            name='quarter',
            field=models.IntegerField(choices=[(1, 'Q1 (Jan–Mar)'), (2, 'Q2 (Apr–Jun)'), (3, 'Q3 (Jul–Sep)'), (4, 'Q4 (Oct–Dec)')]),
        ),
        migrations.AlterField(
            model_name='quarterlyreport',
            name='year',
            field=models.IntegerField(default=reports.models.get_current_year),
        ),
        migrations.AlterField(
            model_name='uploadeddocumentreport',
            name='year',
            field=models.IntegerField(default=reports.models.get_current_year),
        ),
    ]
