# Generated by Django 5.2.1 on 2026-07-14 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_batchuploadfile_alter_channelcoverage_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='annualcategoryreport',
            name='category',
            field=models.CharField(choices=[('all', 'Combined Report'), ('social_media', 'Social Media Only'), ('digital_print', 'Digital Print Only'), ('physical_newspaper', 'Physical Newspaper Only')], default='all', help_text='Selected category scope for this report', max_length=50),
        ),
    ]
