# Generated by Django 5.2.1 on 2026-07-19 11:38

import reports.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_seminareventreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelcoverage',
            name='year',
            field=models.IntegerField(default=reports.models.get_current_year),
        ),
        migrations.AlterField(
            model_name='monthlyreport',
            name='year',
            field=models.IntegerField(default=reports.models.get_current_year),
        ),
        migrations.AlterField(
            model_name='newspapercoverage',
            name='year',
            field=models.IntegerField(default=reports.models.get_current_year),
        ),
        migrations.AlterField(
            model_name='pressrelease',
            name='year',
            field=models.IntegerField(default=reports.models.get_current_year),
        ),
        migrations.AlterField(
            model_name='quarterlyreport',
            name='quarter',
            field=models.IntegerField(choices=[(1, 'Q1 (Jan–Mar)'), (2, 'Q2 (Apr–Jun)'), (3, 'Q3 (Jul–Sep)'), (4, 'Q4 (Oct–Dec)')]),
        ),
        migrations.AlterField(
            model_name='quarterlyreport',
            name='year',
            field=models.IntegerField(default=reports.models.get_current_year),
        ),
        migrations.AlterField(
            model_name='uploadeddocumentreport',
            name='year',
            field=models.IntegerField(default=reports.models.get_current_year),
        ),
    ]
